name: Build Packager
description: Builds a packager docker container

inputs:
  go:
    description: The version of go to build
    required: true

  tag:
    description: The container tag
    required: true

  file:
    description: The Dockerfile
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: choria/packager:${{ inputs.tag }}
        file: ${{ inputs.file }}
        build-args: |
          GOVERSION=${a {inputs.go }}
