name: Builders

on:
  push:
    branches:
      - main

env:
  GO_VERSION: "1.18.0"
  TAG: "1.18"

jobs:
  bullseye_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/build-packager
        with:
          file: Dockerfile.bullseye-go
          go: ${{ env.GO_VERSION }}
          tag: bullseye-go${{ env.TAG }}
          hub_user: ${{ secrets.DOCKERHUB_USERNAME }}
          hub_password: ${{ secrets.DOCKERHUB_TOKEN }}

  buster_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/build-packager
        with:
          file: Dockerfile.buster-go
          go: ${{ env.GO_VERSION }}
          tag: buster-go${{ env.TAG }}
          hub_user: ${{ secrets.DOCKERHUB_USERNAME }}
          hub_password: ${{ secrets.DOCKERHUB_TOKEN }}

  debian_go:
    needs:
      - buster_go

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/build-packager
        with:
          file: Dockerfile.debian-go
          go: ${{ env.GO_VERSION }}
          tag: debian-go${{ env.TAG }}
          hub_user: ${{ secrets.DOCKERHUB_USERNAME }}
          hub_password: ${{ secrets.DOCKERHUB_TOKEN }}

  stretch_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/build-packager
        with:
          file: Dockerfile.stretch-go
          go: ${{ env.GO_VERSION }}
          tag: stretch-go${{ env.TAG }}
          hub_user: ${{ secrets.DOCKERHUB_USERNAME }}
          hub_password: ${{ secrets.DOCKERHUB_TOKEN }}

  xenial_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/build-packager
        with:
          file: Dockerfile.xenial-go
          go: ${{ env.GO_VERSION }}
          tag: xenial-go${{ env.TAG }}
          hub_user: ${{ secrets.DOCKERHUB_USERNAME }}
          hub_password: ${{ secrets.DOCKERHUB_TOKEN }}

  focal_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/build-packager
        with:
          file: Dockerfile.focal-go
          go: ${{ env.GO_VERSION }}
          tag: focal-go${{ env.TAG }}
          hub_user: ${{ secrets.DOCKERHUB_USERNAME }}
          hub_password: ${{ secrets.DOCKERHUB_TOKEN }}

  el7_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/build-packager
        with:
          file: Dockerfile.el7-go
          go: ${{ env.GO_VERSION }}
          tag: el7-go${{ env.TAG }}
          hub_user: ${{ secrets.DOCKERHUB_USERNAME }}
          hub_password: ${{ secrets.DOCKERHUB_TOKEN }}

  el7_puppet_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/build-packager
        with:
          file: Dockerfile.el7-puppet-go
          go: ${{ env.GO_VERSION }}
          tag: el7-puppet-go${{ env.TAG }}
          hub_user: ${{ secrets.DOCKERHUB_USERNAME }}
          hub_password: ${{ secrets.DOCKERHUB_TOKEN }}

  el8_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/build-packager
        with:
          file: Dockerfile.el8-go
          go: ${{ env.GO_VERSION }}
          tag: el8-go${{ env.TAG }}
          hub_user: ${{ secrets.DOCKERHUB_USERNAME }}
          hub_password: ${{ secrets.DOCKERHUB_TOKEN }}
