name: Builders

on:
  push:
    branches:
      - main

env:
  GO_VERSION: "1.17.2"
  TAG: "1.17"

jobs:
  bullseye_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/build-packager
        with:
          file: Dockerfile.bullseye-go
          go: ${{ env.GO_VERSION }}
          tag: bullseye-go${{ env.TAG }}

  el8_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/build-packager
        with:
          file: Dockerfile.el8-go
          go: ${{ env.GO_VERSION }}
          tag: el8-go${{ env.TAG }}
